// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0m8ppazA7P7b6ogD7k82QYyrTfUilGA8',
    appId: '1:259644665729:web:007593bbeea0ea17be8280',
    messagingSenderId: '259644665729',
    projectId: 'mar10-89ff8',
    authDomain: 'mar10-89ff8.firebaseapp.com',
    storageBucket: 'mar10-89ff8.appspot.com',
    measurementId: 'G-RKSM99VEZ6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4JIzA0sAN2SH2zsvpLuNq5MQSIay22w0',
    appId: '1:259644665729:android:ba675d8358e1b398be8280',
    messagingSenderId: '259644665729',
    projectId: 'mar10-89ff8',
    storageBucket: 'mar10-89ff8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdO42pVWbl_K0Ecnx1TLT3ucnEFaGnD0M',
    appId: '1:259644665729:ios:61c79db9b618abfdbe8280',
    messagingSenderId: '259644665729',
    projectId: 'mar10-89ff8',
    storageBucket: 'mar10-89ff8.appspot.com',
    iosBundleId: 'com.example.loginSignup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdO42pVWbl_K0Ecnx1TLT3ucnEFaGnD0M',
    appId: '1:259644665729:ios:a3d6dc94beb1e1f2be8280',
    messagingSenderId: '259644665729',
    projectId: 'mar10-89ff8',
    storageBucket: 'mar10-89ff8.appspot.com',
    iosBundleId: 'com.example.loginSignup.RunnerTests',
  );
}
